### ISSUE TITLE
Google Tasks API Typings

### ISSUE THREAD

**Issue by Maxim-Mazurok** [hisomura/google-tasks-app#1]
Hello, @hisomura! First of all, thank you for your interest in the [google-api-typings-generator](https://github.com/Maxim-Mazurok/google-api-typings-generator) project!

I can see that you have generated [tasks.d.ts](https://github.com/hisomura/google-tasks-app/blob/main/src/lib/tasks.d.ts) file, and I thought I'd let you know that now you can just use this NPM package: [@maxim_mazurok/gapi.client.tasks](https://www.npmjs.com/package/@maxim_mazurok/gapi.client.tasks)

After https://github.com/microsoft/DefinitelyTyped-tools/pull/183 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49915 are merged - you'll be able to use @types/gapi.client.tasks instead, which will be just a reference to @maxim_mazurok/gapi.client.tasks

And if you find anything that needs improvement or any other questions - don't hesitate to [open an issue](https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/new) or just ask me in the comments here :) Cheers!

**Comment by hisomura** [comment]
Thank you very much for your great job and for telling me the information! 
I will use [@maxim_mazurok/gapi.client.tasks](https://www.npmjs.com/package/@maxim_mazurok/gapi.client.tasks) immediately.
I am looking forward to the day when I will be able to use @types/gapi.client.tasks.

**Comment by Maxim-Mazurok** [comment]
Hello! [@types/gapi.client.tasks](https://www.npmjs.com/package/@types/gapi.client.tasks) has been finally published :)
Please, give it a try!

**Comment by hisomura** [comment]
Great! 
I have used it immediately.
Thanks for letting me know it!
